### PR TITLE
made 404 more OwO-ish

### PR DESCRIPTION
**Pull request by sr229**
I'm sorry :cry:

### CODE REVIEW

**Comment by aurieh** [comment]
Not meme enough, smh

**Comment by sr229** [comment]
cri

**Comment by zet4** [comment]
needs more memes, pls fix

**Comment by jakeoid** [comment]
smh, you didnt edit the source/pug.

( also im not contributor so I cant accept PR anyway :^( )

**Comment by aurieh** [comment]
@jakeoid heck https://owo.whats-th.is/52de85.png

**Comment by jakeoid** [comment]
wait wha..

https://i.am-a.ninja/7cd449.png

**Comment by zet4** [comment]
Yes, please apply your changes to the [source](https://github.com/whats-this/landing/blob/master/src/views/404.pug) as well.

**Comment by sr229** [comment]
how2becontrib a

**Comment by deansheather** [comment]
Why not do this? I think this was suggested, and I like it more than this.
```
h1 OwO, whats th-
h3 Oh, there's nothing here.
```

**Comment by aurieh** [comment]
@deansheather @martmists suggested that,  I think it would fit in quite well.

**Comment by sr229** [comment]
@deansheather it's more apporpriate for the meme iirc

**Comment by deansheather** [comment]
Alright, I like that one better than this one and Aurieh seems to agree so I'll approve this when that's been changed.

**Comment by sr229** [comment]
image
brb lemme calculate the probability of getting bent after this PR

**Pull request merged**
